### ISSUE TITLE
Possible helpful framework

### ISSUE THREAD

**Issue by pvjosue** [TuragaLab/chromatix#15]
Dear TurugaLab, 

Here you can find [WaveBlocks](https://github.com/pvjosue/WaveBlocks) framework, another differential wave optics simulator. 
Maybe you can get some ideas and hints from the implementation :) 

I will give chromatix a try and will be happy to help if required.

Cheers!
Josue

**Comment by diptodip** [comment]
Hi Josué,

Thanks for sharing --- looks like we have a lot of similar ideas!

We actually also originally built a [library in PyTorch](https://github.com/TuragaLab/snapshotscope) for simulating a 4f microscope, which we scaled to multiple GPUs in order to [optimize large PSFs for snapshot microscopy using deep learning](https://openreview.net/forum?id=Kx1VCs1treH).

This turned out to be pretty slow for various reasons, and we've since found that `jax` results in much more performant (and memory efficient) simulations for optics --- and also makes it very easy to parallelize those simulations both on a single GPU and across multiple GPUs.

If you do try out `chromatix`, I'd love to know what you think! That said, we're in very early stages. There's a lot of stuff that's missing right now that your library can do (like microlens arrays). We'll be working on those kinds of things soon. I'm happy to answer any questions you might have (my email: debd@janelia.hhmi.org).

Best,
Diptodip
