### ISSUE TITLE
potato_chip NaNs

### ISSUE THREAD

**Issue by schneidermc** [TuragaLab/chromatix#25]
The function for the potato_chip phase mask outputs NaN values if called with unsuitable spacing value.

**Comment by diptodip** [comment]
A suitable call to `potato_chip()` you can try for now is:

```python
potato_chip((1, 3840, 3840, 1), 0.03205128205, 0.532, 1.33, 100.0, 0.8)
```

As you can see the spacing needs to be very small for the values we've chosen. We can't really choose this value for the user because it depends on the system they want to use this phase mask for, but we can add an assertion to check for `NaNs` which gives a warning about the sampling with a pointer to a utility function to calculate the correct spacing.

**Comment by diptodip** [comment]
I think this is already correct, so I'm closing it
